# Dockerfile para desarrollo
FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
    git \
    curl \
    libxml2-dev \
    zip \
    unzip \
    oniguruma-dev \
    mysql-client \
    $PHPIZE_DEPS

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath opcache

RUN apk add --no-cache pcre-dev \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del pcre-dev $PHPIZE_DEPS

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN apk add --no-cache netcat-openbsd

COPY docker/entrypoint-dev.sh /usr/local/bin/entrypoint-dev.sh
RUN chmod +x /usr/local/bin/entrypoint-dev.sh

WORKDIR /var/www/html

RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

RUN composer install

EXPOSE 8000

ENTRYPOINT ["/usr/local/bin/entrypoint-dev.sh"]


CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]


